# Example Job for running the NVIDIA SMI tool inside a container
# 
# This version of the Job requests a display device from the WDDM device plugin. For a version that
# requests a compute-only device from the MCDM device plugin, see the file `nvidia-smi-mcdm.yml`
# 
# NOTE: this Job will only work when the device allocated by the WDDM device plugin is an NVIDIA GPU,
# otherwise the executable `nvidia-smi.exe` won't exist and the Pod will fail to start.

apiVersion: batch/v1
kind: Job
metadata:
  name: example-nvidia-smi
spec:
  template:
    spec:
      containers:
      - name: example-nvidia-smi
        image: "mcr.microsoft.com/windows/servercore:ltsc2022"
        command: ["nvidia-smi.exe"]
        resources:
          limits:
            directx.microsoft.com/display: 1
      nodeSelector:
        "kubernetes.io/os": windows
      restartPolicy: Never
  backoffLimit: 0
